### PR TITLE
init commit of edits for exposing C api

### PR DESCRIPTION
**Pull request by ChrisMuir**
Related to issue [#67](https://github.com/markvanderloo/stringdist/issues/67). As mentioned before, I created this branch just to get the ball rolling on the API, so am happy to make edits (or if it needs to be torn down and redone, that's cool too 😄 ).

### CODE REVIEW

**Comment by markvanderloo** [comment]
Hmm can't merge because of a failing test (I'm on my phone now).

**Comment by ChrisMuir** [comment]
Hmm, all Travis tests passed, I think it's just that test coverage dropped by 0.2%. I think the drop is due to the `zzz.R` file I added, as the guts of `.onUnload` is not covered, see [here](https://coveralls.io/jobs/35780081/source_files/860594701#L2).

**Comment by markvanderloo** [comment]
I just merged it. There was no real fail but a minor drop in the test coverage (naturally). Apparently it is not possible to merge from the phone when that happens. In any case I'm back in town and I'm able to respond much quicker. I'll have a good look at WRE on the C API this week. Looking forward to getting this out there!

**Comment by ChrisMuir** [comment]
👍 Sounds great!

Yeah I think the coverage drop was the `zzz.R` file I added, see [here](https://coveralls.io/jobs/35780081/source_files/860594701#L2). No biggie.

**Pull request merged**
